//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 02:18:43 AM EET 
//


package edu.pragmatic.xml.homework.students.model;

import javax.xml.bind.annotation.XmlRegistry;


@XmlRegistry
public class ObjectFactory {


    public ObjectFactory() {
    }

    public School createSchool() {
        return new School();
    }

    public School.Exams createExamContainer() {
        return new School.Exams();
    }

    public School.Exams.Exam createExam() {
        return new School.Exams.Exam();
    }

    public School.Students createSchoolStudents() {
        return new School.Students();
    }

    public School.Teachers createSchoolTeachers() {
        return new School.Teachers();
    }

    public School.Exams.Exam.Students createSchoolExamsExamStudents() {
        return new School.Exams.Exam.Students();
    }

    public School.Students.Student createSchoolStudentsStudent() {
        return new School.Students.Student();
    }

    public School.Teachers.Teacher createSchoolTeachersTeacher() {
        return new School.Teachers.Teacher();
    }

}
